-- Passwordless entry points, generated by staff and sent over WhatsApp, for
-- patients who already have a portal account but can't be relied on to have
-- their password handy on a phone. Visiting the link signs them straight
-- into their own account — same session a password login creates — landing
-- them on whatever the portal already shows first, including the GDPR gate.
--
-- Deliberately reusable until expiry rather than single-use: a patient
-- closing the browser mid-flow on a flaky mobile connection shouldn't need
-- staff to regenerate the link just to try again.
create table magic_links (
  token      text        primary key,
  account_id uuid        not null references accounts (id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index magic_links_account_idx on magic_links (account_id);
