#!/usr/bin/env python3
"""Converts netlify.toml's redirect/header rules into Cloudflare Pages'
native _redirects and _headers files.

Run after editing netlify.toml (new WordPress redirect, new header rule,
etc.) so the two hosts stay in sync:

    python3 tools/build-cf-redirects.py
"""
import os
import sys
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def build_redirects(cfg):
    # Netlify needed pretty_urls = true to serve /rinoplastie from
    # rinoplastie.html. Cloudflare Pages does this natively — confirmed by
    # running the actual thing (`wrangler pages dev`), not by assumption:
    # requesting /contact.html there 308s to /contact on its own, with zero
    # rules of ours. Adding an explicit "/rinoplastie -> /rinoplastie.html
    # 200" rule on top of that native behaviour does not just duplicate it,
    # it fights it — the rewrite serves the .html file, Pages' own layer
    # then redirects that .html response back to the extensionless URL,
    # which matches our rule again: an infinite 308 loop. So: no clean-URL
    # rules here at all, by design, not by oversight.
    lines = [
        '# Generated by tools/build-cf-redirects.py from netlify.toml — do not edit by hand.',
        '# Cloudflare Pages reads this file from the publish directory root.',
        '# First match wins, so exact/literal rules are listed before wildcards.',
        '#',
        '# No clean-URL (/page -> /page.html) rules here on purpose — Pages',
        '# already serves and canonicalises extensionless HTML natively.',
        '# Adding them back causes an infinite redirect loop; see git history',
        '# on this file before reintroducing anything like that.',
        '',
        '# --- from netlify.toml [[redirects]] (WordPress cutover map, and',
        '# excluding server/, tools/ and the internal .md docs from being served) ---',
    ]
    for r in cfg.get('redirects', []):
        status = r.get('status', 301)
        lines.append(f"{r['from']} {r['to']} {status}")

    return '\n'.join(lines) + '\n'


def build_headers(cfg):
    lines = [
        '# Generated by tools/build-cf-redirects.py from netlify.toml — do not edit by hand.',
        '',
    ]
    for block in cfg.get('headers', []):
        lines.append(block['for'])
        for k, v in block.get('values', {}).items():
            lines.append(f'  {k}: {v}')
        lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


def main():
    with open(os.path.join(ROOT, 'netlify.toml'), 'rb') as fh:
        cfg = tomllib.load(fh)

    redirects_path = os.path.join(ROOT, '_redirects')
    headers_path = os.path.join(ROOT, '_headers')

    redirects = build_redirects(cfg)
    headers = build_headers(cfg)

    with open(redirects_path, 'w', encoding='utf-8') as fh:
        fh.write(redirects)
    with open(headers_path, 'w', encoding='utf-8') as fh:
        fh.write(headers)

    n_lines = sum(1 for l in redirects.splitlines() if l and not l.startswith('#'))
    print(f'_redirects written: {n_lines} rules')
    print(f'_headers written: {len(cfg.get("headers", []))} blocks')


if __name__ == '__main__':
    sys.exit(main())
