#!/usr/bin/env python3
"""Converts netlify.toml's redirect/header rules into an Apache .htaccess
pair for cPanel (Cyberfolks) hosting — netlify.toml stays the single
hand-edited source of truth, same as tools/build-cf-redirects.py did for
Cloudflare Pages.

Run after editing netlify.toml (new WordPress redirect, new header rule,
new page, etc.) so the live host stays in sync:

    python3 tools/build-htaccess.py

Writes two files:
  .htaccess             — site-wide headers, the WordPress redirect map,
                           clean-URL serving, and the custom 404 page.
  materials/.htaccess   — the materials/-only Cache-Control header.
    (mod_headers directory scoping needs its own .htaccess per
    directory; <Location>/<LocationMatch> blocks are not allowed
    inside .htaccess context at all.)
"""
import os
import re
import sys
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def to_pattern(path):
    """Turns a netlify.toml `from` path into an anchored Apache regex.

    Every `from` in this file is either a literal path ("/exact/path",
    optionally with a trailing slash) or a literal path ending in "/*"
    (the only wildcard shape netlify.toml uses here — confirmed by
    grepping for '*' anywhere else in a `from` value: there is none).
    Escaping first and special-casing the trailing "*" after means a
    literal "." (as in "/DOCUMENTATIE-TEHNICA.md") can't accidentally
    match any character.

    The leading "/" is stripped before building the pattern: a
    per-directory .htaccess (as opposed to a <VirtualHost> block) sees
    URL-paths with that directory's own prefix already removed, so a
    request for "/rinoplastie" arrives at RewriteRule here as
    "rinoplastie" — a pattern anchored on "^/rinoplastie$" would never
    match anything, silently.
    """
    path = path.lstrip('/')
    if path.endswith('*'):
        base = re.escape(path[:-1].rstrip('/'))
        return f'^{base}(/.*)?$'
    return f'^{re.escape(path)}$'


APEX_HOST = 'tratamente-turcia.ro'
WWW_HOST = 'www.tratamente-turcia.ro'


def build_htaccess(cfg):
    lines = [
        '# Generated by tools/build-htaccess.py from netlify.toml — do not edit by hand.',
        '# Rebuild after any change to netlify.toml.',
        '',
        'RewriteEngine On',
        '',
        '# --- Force the apex to www, which is what actually runs the site ---',
        '#',
        "# Cyberfolks is a fallback host now (see this file's own top comment) —",
        '# the real site is on Railway, reached via CNAMEs on www and platforma.',
        "# A CNAME can't target a bare apex, so tratamente-turcia.ro itself still",
        '# resolves here, and this rule is what sends it on to www instead of',
        "# serving this host's own (increasingly stale) copy of the site. It has",
        '# to be the very first rule in the file: every other rule below either',
        '# redirects (some real page) or serves a file straight off disk, and',
        "# whichever fires first wins with `[L]` — so if this ran after them, a",
        '# request matching any real page would never reach it. (This is exactly',
        "# the bug cPanel's own Redirect tool shipped by default: it appends",
        '# this same rule at the bottom of the file instead of the top.)',
        f'RewriteCond %{{HTTP_HOST}} ^{re.escape(APEX_HOST)}$',
        f'RewriteRule ^(.*)$ https://{WWW_HOST}/$1 [R=301,L]',
        '',
        '# --- Security headers (netlify.toml [[headers]] for = "/*") ---',
    ]
    for block in cfg.get('headers', []):
        if block['for'] != '/*':
            continue
        for k, v in block.get('values', {}).items():
            lines.append(f'Header always set {k} "{v}"')
    lines.append('')

    lines.append('# --- WordPress cutover redirect map (netlify.toml [[redirects]]) ---')
    lines.append('# Exact rules and wildcard rules are both anchored regexes, evaluated')
    lines.append('# in the order they appear below (same order as netlify.toml), so a')
    lines.append('# rule never shadows one listed after it.')
    for r in cfg.get('redirects', []):
        status = r.get('status', 301)
        pattern = to_pattern(r['from'])
        lines.append(f"RewriteRule {pattern} {r['to']} [R={status},L]")
    lines.append('')

    lines.append('# --- Clean URLs: serve /page from page.html without redirecting ---')
    lines.append('# (an internal rewrite, invisible to the client — not a redirect, so')
    lines.append("# it can't loop against the rule below the way a public 200/301 pair")
    lines.append('# did on Cloudflare; see git history on that host\'s config.)')
    lines.append('RewriteCond %{REQUEST_FILENAME} !-f')
    lines.append('RewriteCond %{REQUEST_FILENAME} !-d')
    lines.append('RewriteCond %{REQUEST_FILENAME}\\.html -f')
    lines.append('RewriteRule ^(.*)$ $1.html [L]')
    lines.append('')
    lines.append('# The reverse direction: a request for the literal .html file redirects')
    lines.append('# to the extensionless URL, so every canonical tag on the site (all of')
    lines.append('# them extensionless) matches what is actually served. index.html is')
    lines.append('# special-cased ahead of the generic rule below it: that one strips just')
    lines.append('# the extension, which would send it to "/index" instead of "/".')
    lines.append('RewriteRule ^index\\.html$ / [R=301,L]')
    lines.append('RewriteCond %{THE_REQUEST} \\s/+(.+?)\\.html[\\s?] [NC]')
    lines.append('RewriteRule ^ /%1 [R=301,L]')
    lines.append('')

    lines.append('# --- Custom 404 ---')
    lines.append('ErrorDocument 404 /404.html')
    lines.append('')

    return '\n'.join(lines) + '\n'


def build_materials_htaccess(cfg):
    lines = [
        '# Generated by tools/build-htaccess.py from netlify.toml — do not edit by hand.',
        '',
    ]
    for block in cfg.get('headers', []):
        if block['for'] != '/materials/*':
            continue
        for k, v in block.get('values', {}).items():
            lines.append(f'Header always set {k} "{v}"')
    return '\n'.join(lines).rstrip() + '\n'


def main():
    with open(os.path.join(ROOT, 'netlify.toml'), 'rb') as fh:
        cfg = tomllib.load(fh)

    htaccess = build_htaccess(cfg)
    materials_htaccess = build_materials_htaccess(cfg)

    with open(os.path.join(ROOT, '.htaccess'), 'w', encoding='utf-8') as fh:
        fh.write(htaccess)

    materials_dir = os.path.join(ROOT, 'materials')
    os.makedirs(materials_dir, exist_ok=True)
    with open(os.path.join(materials_dir, '.htaccess'), 'w', encoding='utf-8') as fh:
        fh.write(materials_htaccess)

    n_rules = sum(1 for r in cfg.get('redirects', []))
    print(f'.htaccess written: {n_rules} redirect rules')
    print('materials/.htaccess written')


if __name__ == '__main__':
    sys.exit(main())
